### ISSUE TITLE
Screenshot of the modem page?

### ISSUE THREAD

**Issue by csmarshall** [theY4Kman/netdata-arris-modem-plugin-python#2]
I'm going to make a fork that works for the 8200, but I wondered if you could post a picture of the page, you can munge the #s to whatever you want, but the values, or even just the raw HTML would be super helpful.

**Comment by csmarshall** [comment]
I got it, no need, resolving.

**Comment by theY4Kman** [comment]
Noice! Glad you got some use out of this plugin :) It's really helped me prepare for the worst once the uncorrectables skyrocket, and I know my stupid cable is about to drop again :P

**Comment by theY4Kman** [comment]
re: [this comment](https://github.com/csmarshall/netdata-arris-surfboard-modem-plugin-python/blob/b3d1494fcd9fd1d05be5f5fbc32160987f3dafc2/arris_surfboard_modem.chart.py#L60-L61)
```py
# Why would we want an order different than what we already defined 🤷 ?
ORDER = [i for i in CHARTS]
```

I think defining `ORDER` separately is something I took from a tutorial / example plugin code. It definitely makes more sense to just take the order from `CHARTS` :P

FYI: an equivalent way to express that is `ORDER = list(CHARTS)` — though it may be easier to read as `ORDER = list(CHARTS.keys())`.

**Comment by csmarshall** [comment]
Oh yea, I know it was a requirement from the plugin classes, it's more just in this case why I would one collect data in one order and show it in another? :/  I went ahead and posted the current working version for my model, if your UI is similar you might be able to just drop it in if you want the extra functionality (upstreams?), but otherwise it was a fun little reminder of how annoying XML can be. :)

As far as casting a the dict items to a list, ya, that works too, I just have a habit of avoiding forcibly casting things if I can, I'm still unsure what the "most pythonic" way is to do it is, but I know calling .keys() is not the most...python3 way of dealing with it?
